name: rochambeau
services:
  main:
    type: compose
    services:
      image: ruby:2.7
      command: tail -f /dev/null
    build:
      - bundle install --gemfile=/app/Gemfile
      - chmod +x /app/bin/rochambeau
tooling:
  rochambeau:
    service: main
    cmd: ruby /app/lib/rochambeau.rb
  irb:
    service: main
    cmd: irb
  rake:
    service: main
  bundle:
    service: main
    dir: /app
  test:
    service: main
    cmd: bundle exec rspec
    dir: /app
  lint:
    service: main
    cmd: bundle exec rubocop
    dir: /app
  srb:
    service: main
    cmd: bundle exec srb
    dir: /app
