AllCops:
  NewCops: enable
  SuggestExtensions: false

Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - spec/rochambeau/option_spec.rb

# Allow substantially complicated code.
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Exclude:
    - './spec/**/*.rb'

Style/Documentation:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/HashEachMethods:
  Exclude:
    - spec/rochambeau/option_spec.rb
