# Allow substantially complicated code.
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Max: 64
  Exclude:
    - './spec/**/*.rb'

Metrics/LineLength:
  Exclude:
    - './spec/**/*.rb'

Metrics/MethodLength:
  Max: 64
