AllCops:
  NewCops: enable
  SuggestExtensions: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/LineLength:
  Exclude:
    - './spec/**/*.rb'

Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - spec/rochambeau/option_spec.rb
Lint/DuplicateBranch:
  Exclude:
    - lib/rochambeau/option.rb

# Allow substantially complicated code.
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/HashEachMethods:
  Exclude:
    - spec/rochambeau/option_spec.rb
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
