AllCops:
  NewCops: enable

# Allow substantially complicated code.
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Exclude:
    - './spec/**/*.rb'
